#ifndef DONNEES_DISCO_TESTS_HPP_INCLUDED
#define DONNEES_DISCO_TESTS_HPP_INCLUDED

void test_creation_morceau_entree_complete();
void test_creation_morceau_entree_espaces_partout();
void test_creation_morceau_entree_chanson_artiste();
void test_creation_morceau_entree_chanson_uniquement();
void test_creation_morceau_entree_chanson_artiste_barres_collees();
void test_creation_morceau_entree_vide();
void test_charge_configuration_cherche_fichier();

#endif
